CREATE TABLE IF NOT EXISTS role_menu_access (
  role ENUM('PENDAMPING') NOT NULL,
  menu_key VARCHAR(80) NOT NULL,
  is_enabled TINYINT(1) NOT NULL DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (role, menu_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

