// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/absensi" | "/art" | "/backup" | "/dashboard" | "/final-closing" | "/hak-akses" | "/import" | "/kelompok" | "/laporan-p2k2" | "/login" | "/logs" | "/maintenance" | "/pendamping" | "/profil-pendamping" | "/rekap-p2k2" | "/rekon" | "/server-monitor" | "/settings" | "/storage" | "/surat" | "/tracking" | "/users" | "/verifikasi-kesehatan" | "/wilayah"
type AppRouteHandlerRoutes = "/api/art/[noKk]" | "/api/auth/heartbeat" | "/api/auth/login" | "/api/auth/logout" | "/api/backup" | "/api/dashboard" | "/api/hak-akses" | "/api/import/art" | "/api/import/final-closing" | "/api/import/final-closing/clear" | "/api/kelompok" | "/api/kelompok/[id]" | "/api/kelompok/[id]/members" | "/api/kelompok/sync-active" | "/api/kpm" | "/api/kpm/map" | "/api/p2k2/file" | "/api/p2k2/reports" | "/api/pendamping/[id]" | "/api/pendamping/import" | "/api/pendamping/status" | "/api/rekon" | "/api/server-monitor" | "/api/settings/active-period" | "/api/settings/profile" | "/api/surat" | "/api/surat/file" | "/api/tasks" | "/api/tasks/[id]" | "/api/tasks/[id]/complete" | "/api/verifikasi-kesehatan/file" | "/api/verifikasi-kesehatan/identitas" | "/api/verifikasi-kesehatan/kunjungan" | "/api/verifikasi-kesehatan/preview-pdf"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/absensi": {}
  "/api/art/[noKk]": { "noKk": string; }
  "/api/auth/heartbeat": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/backup": {}
  "/api/dashboard": {}
  "/api/hak-akses": {}
  "/api/import/art": {}
  "/api/import/final-closing": {}
  "/api/import/final-closing/clear": {}
  "/api/kelompok": {}
  "/api/kelompok/[id]": { "id": string; }
  "/api/kelompok/[id]/members": { "id": string; }
  "/api/kelompok/sync-active": {}
  "/api/kpm": {}
  "/api/kpm/map": {}
  "/api/p2k2/file": {}
  "/api/p2k2/reports": {}
  "/api/pendamping/[id]": { "id": string; }
  "/api/pendamping/import": {}
  "/api/pendamping/status": {}
  "/api/rekon": {}
  "/api/server-monitor": {}
  "/api/settings/active-period": {}
  "/api/settings/profile": {}
  "/api/surat": {}
  "/api/surat/file": {}
  "/api/tasks": {}
  "/api/tasks/[id]": { "id": string; }
  "/api/tasks/[id]/complete": { "id": string; }
  "/api/verifikasi-kesehatan/file": {}
  "/api/verifikasi-kesehatan/identitas": {}
  "/api/verifikasi-kesehatan/kunjungan": {}
  "/api/verifikasi-kesehatan/preview-pdf": {}
  "/art": {}
  "/backup": {}
  "/dashboard": {}
  "/final-closing": {}
  "/hak-akses": {}
  "/import": {}
  "/kelompok": {}
  "/laporan-p2k2": {}
  "/login": {}
  "/logs": {}
  "/maintenance": {}
  "/pendamping": {}
  "/profil-pendamping": {}
  "/rekap-p2k2": {}
  "/rekon": {}
  "/server-monitor": {}
  "/settings": {}
  "/storage": {}
  "/surat": {}
  "/tracking": {}
  "/users": {}
  "/verifikasi-kesehatan": {}
  "/wilayah": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
