// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(app)/absensi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/absensi">> = Specific
  const handler = {} as typeof import("../../app/(app)/absensi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/art/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/art">> = Specific
  const handler = {} as typeof import("../../app/(app)/art/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/backup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/backup">> = Specific
  const handler = {} as typeof import("../../app/(app)/backup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/(app)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/final-closing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/final-closing">> = Specific
  const handler = {} as typeof import("../../app/(app)/final-closing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/hak-akses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hak-akses">> = Specific
  const handler = {} as typeof import("../../app/(app)/hak-akses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/import">> = Specific
  const handler = {} as typeof import("../../app/(app)/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/kelompok/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kelompok">> = Specific
  const handler = {} as typeof import("../../app/(app)/kelompok/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/laporan-p2k2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/laporan-p2k2">> = Specific
  const handler = {} as typeof import("../../app/(app)/laporan-p2k2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logs">> = Specific
  const handler = {} as typeof import("../../app/(app)/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/pendamping/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pendamping">> = Specific
  const handler = {} as typeof import("../../app/(app)/pendamping/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/profil-pendamping/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profil-pendamping">> = Specific
  const handler = {} as typeof import("../../app/(app)/profil-pendamping/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/rekap-p2k2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rekap-p2k2">> = Specific
  const handler = {} as typeof import("../../app/(app)/rekap-p2k2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/rekon/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rekon">> = Specific
  const handler = {} as typeof import("../../app/(app)/rekon/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/server-monitor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/server-monitor">> = Specific
  const handler = {} as typeof import("../../app/(app)/server-monitor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/(app)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/storage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/storage">> = Specific
  const handler = {} as typeof import("../../app/(app)/storage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/surat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/surat">> = Specific
  const handler = {} as typeof import("../../app/(app)/surat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/tracking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tracking">> = Specific
  const handler = {} as typeof import("../../app/(app)/tracking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/users">> = Specific
  const handler = {} as typeof import("../../app/(app)/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/verifikasi-kesehatan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verifikasi-kesehatan">> = Specific
  const handler = {} as typeof import("../../app/(app)/verifikasi-kesehatan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/wilayah/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wilayah">> = Specific
  const handler = {} as typeof import("../../app/(app)/wilayah/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/maintenance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance">> = Specific
  const handler = {} as typeof import("../../app/maintenance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/art/[noKk]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/art/[noKk]">> = Specific
  const handler = {} as typeof import("../../app/api/art/[noKk]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/heartbeat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/heartbeat">> = Specific
  const handler = {} as typeof import("../../app/api/auth/heartbeat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/backup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backup">> = Specific
  const handler = {} as typeof import("../../app/api/backup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard">> = Specific
  const handler = {} as typeof import("../../app/api/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/hak-akses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hak-akses">> = Specific
  const handler = {} as typeof import("../../app/api/hak-akses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/import/art/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import/art">> = Specific
  const handler = {} as typeof import("../../app/api/import/art/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/import/final-closing/clear/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import/final-closing/clear">> = Specific
  const handler = {} as typeof import("../../app/api/import/final-closing/clear/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/import/final-closing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import/final-closing">> = Specific
  const handler = {} as typeof import("../../app/api/import/final-closing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/kelompok/[id]/members/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kelompok/[id]/members">> = Specific
  const handler = {} as typeof import("../../app/api/kelompok/[id]/members/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/kelompok/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kelompok/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/kelompok/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/kelompok/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kelompok">> = Specific
  const handler = {} as typeof import("../../app/api/kelompok/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/kelompok/sync-active/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kelompok/sync-active">> = Specific
  const handler = {} as typeof import("../../app/api/kelompok/sync-active/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/kpm/map/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kpm/map">> = Specific
  const handler = {} as typeof import("../../app/api/kpm/map/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/kpm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kpm">> = Specific
  const handler = {} as typeof import("../../app/api/kpm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/p2k2/file/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/p2k2/file">> = Specific
  const handler = {} as typeof import("../../app/api/p2k2/file/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/p2k2/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/p2k2/reports">> = Specific
  const handler = {} as typeof import("../../app/api/p2k2/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pendamping/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pendamping/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/pendamping/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pendamping/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pendamping/import">> = Specific
  const handler = {} as typeof import("../../app/api/pendamping/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pendamping/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pendamping/status">> = Specific
  const handler = {} as typeof import("../../app/api/pendamping/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rekon/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rekon">> = Specific
  const handler = {} as typeof import("../../app/api/rekon/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/server-monitor/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/server-monitor">> = Specific
  const handler = {} as typeof import("../../app/api/server-monitor/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/active-period/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/active-period">> = Specific
  const handler = {} as typeof import("../../app/api/settings/active-period/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/profile">> = Specific
  const handler = {} as typeof import("../../app/api/settings/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/surat/file/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/surat/file">> = Specific
  const handler = {} as typeof import("../../app/api/surat/file/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/surat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/surat">> = Specific
  const handler = {} as typeof import("../../app/api/surat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tasks/[id]/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]/complete">> = Specific
  const handler = {} as typeof import("../../app/api/tasks/[id]/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tasks/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/tasks/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks">> = Specific
  const handler = {} as typeof import("../../app/api/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/verifikasi-kesehatan/file/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/verifikasi-kesehatan/file">> = Specific
  const handler = {} as typeof import("../../app/api/verifikasi-kesehatan/file/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/verifikasi-kesehatan/identitas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/verifikasi-kesehatan/identitas">> = Specific
  const handler = {} as typeof import("../../app/api/verifikasi-kesehatan/identitas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/verifikasi-kesehatan/kunjungan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/verifikasi-kesehatan/kunjungan">> = Specific
  const handler = {} as typeof import("../../app/api/verifikasi-kesehatan/kunjungan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/verifikasi-kesehatan/preview-pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/verifikasi-kesehatan/preview-pdf">> = Specific
  const handler = {} as typeof import("../../app/api/verifikasi-kesehatan/preview-pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
